"""add indexes on fk columns

Revision ID: 6d17b6bbe7d5
Revises: ce89e4265368
Create Date: 2026-07-14 22:50:08.595316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d17b6bbe7d5'
down_revision: Union[str, Sequence[str], None] = 'ce89e4265368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_examples_word_id'), 'examples', ['word_id'], unique=False)
    op.create_index(op.f('ix_translations_word_id'), 'translations', ['word_id'], unique=False)
    op.create_index(op.f('ix_words_user_id'), 'words', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_words_user_id'), table_name='words')
    op.drop_index(op.f('ix_translations_word_id'), table_name='translations')
    op.drop_index(op.f('ix_examples_word_id'), table_name='examples')
    # ### end Alembic commands ###
